---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brand-detection
  namespace: abuse-api-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - branddetection.cset.int.dev-gdcorp.tools
      secretName: cset-wildcard
  rules:
  - host: branddetection.cset.int.dev-gdcorp.tools
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: brand-detection
            port:
              number: 5000
