apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- brand_detection.ingress.yaml

namespace: abuse-api-dev
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/volumeMounts"
      value:
      - name: encryption-keys
        mountPath: /keyfiles
        readOnly: true
    - op: add
      path: "/spec/template/spec/volumes/0"
      value:
        name: encryption-keys
        secret:
          secretName: encryption-key-files
  target:
    kind: Deployment
    name: brand-detection


images:
- name: docker-dcu-local.artifactory.secureserver.net/brand_detection
  newTag: dev

configMapGenerator:
- literals:
  - sysenv=dev
  - REDIS=brand-detection-redis.abuse-api-dev.svc.cluster.local
  - KEYFILE=/keyfiles/key.txt
  - DOMAIN_SERVICE_URL=domainservice.abuse-api-dev.svc.cluster.local:9000
  name: env-specific-values
