# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: domain-service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='domain-service.proto',
  package='domainmessages',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x64omain-service.proto\x12\x0e\x64omainmessages\x1a\x1cgoogle/api/annotations.proto\"F\n\x15SuspendDomainsRequest\x12\x11\n\tdomainids\x18\x01 \x03(\t\x12\x0c\n\x04note\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\"\'\n\x16SuspendDomainsResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"H\n\x17UnSuspendDomainsRequest\x12\x11\n\tdomainids\x18\x01 \x03(\t\x12\x0c\n\x04note\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\")\n\x18UnSuspendDomainsResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"#\n\x11\x44omainInfoRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\"m\n\x12\x44omainInfoResponse\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x11\n\tshopperId\x18\x02 \x01(\t\x12\x10\n\x08\x64omainId\x18\x03 \x01(\x05\x12\x12\n\ncreateDate\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t2\x9f\x03\n\rDomainService\x12\x85\x01\n\x0eSuspendDomains\x12%.domainmessages.SuspendDomainsRequest\x1a&.domainmessages.SuspendDomainsResponse\"$\x82\xd3\xe4\x93\x02\x1e\"\x19/v1/domains/suspenddomain:\x01*\x12\x8d\x01\n\x10UnSuspendDomains\x12\'.domainmessages.UnSuspendDomainsRequest\x1a(.domainmessages.UnSuspendDomainsResponse\"&\x82\xd3\xe4\x93\x02 \"\x1b/v1/domains/unsuspenddomain:\x01*\x12v\n\nDomainInfo\x12!.domainmessages.DomainInfoRequest\x1a\".domainmessages.DomainInfoResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x16/v1/domains/domaininfo:\x01*B\x04Z\x02pbb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_SUSPENDDOMAINSREQUEST = _descriptor.Descriptor(
  name='SuspendDomainsRequest',
  full_name='domainmessages.SuspendDomainsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domainids', full_name='domainmessages.SuspendDomainsRequest.domainids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note', full_name='domainmessages.SuspendDomainsRequest.note', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='domainmessages.SuspendDomainsRequest.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=140,
)


_SUSPENDDOMAINSRESPONSE = _descriptor.Descriptor(
  name='SuspendDomainsResponse',
  full_name='domainmessages.SuspendDomainsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='domainmessages.SuspendDomainsResponse.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=181,
)


_UNSUSPENDDOMAINSREQUEST = _descriptor.Descriptor(
  name='UnSuspendDomainsRequest',
  full_name='domainmessages.UnSuspendDomainsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domainids', full_name='domainmessages.UnSuspendDomainsRequest.domainids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='note', full_name='domainmessages.UnSuspendDomainsRequest.note', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='domainmessages.UnSuspendDomainsRequest.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=255,
)


_UNSUSPENDDOMAINSRESPONSE = _descriptor.Descriptor(
  name='UnSuspendDomainsResponse',
  full_name='domainmessages.UnSuspendDomainsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='domainmessages.UnSuspendDomainsResponse.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=298,
)


_DOMAININFOREQUEST = _descriptor.Descriptor(
  name='DomainInfoRequest',
  full_name='domainmessages.DomainInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='domainmessages.DomainInfoRequest.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=335,
)


_DOMAININFORESPONSE = _descriptor.Descriptor(
  name='DomainInfoResponse',
  full_name='domainmessages.DomainInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='domainmessages.DomainInfoResponse.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shopperId', full_name='domainmessages.DomainInfoResponse.shopperId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domainId', full_name='domainmessages.DomainInfoResponse.domainId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createDate', full_name='domainmessages.DomainInfoResponse.createDate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='domainmessages.DomainInfoResponse.status', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=446,
)

DESCRIPTOR.message_types_by_name['SuspendDomainsRequest'] = _SUSPENDDOMAINSREQUEST
DESCRIPTOR.message_types_by_name['SuspendDomainsResponse'] = _SUSPENDDOMAINSRESPONSE
DESCRIPTOR.message_types_by_name['UnSuspendDomainsRequest'] = _UNSUSPENDDOMAINSREQUEST
DESCRIPTOR.message_types_by_name['UnSuspendDomainsResponse'] = _UNSUSPENDDOMAINSRESPONSE
DESCRIPTOR.message_types_by_name['DomainInfoRequest'] = _DOMAININFOREQUEST
DESCRIPTOR.message_types_by_name['DomainInfoResponse'] = _DOMAININFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SuspendDomainsRequest = _reflection.GeneratedProtocolMessageType('SuspendDomainsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUSPENDDOMAINSREQUEST,
  __module__ = 'domain_service_pb2'
  # @@protoc_insertion_point(class_scope:domainmessages.SuspendDomainsRequest)
  ))
_sym_db.RegisterMessage(SuspendDomainsRequest)

SuspendDomainsResponse = _reflection.GeneratedProtocolMessageType('SuspendDomainsResponse', (_message.Message,), dict(
  DESCRIPTOR = _SUSPENDDOMAINSRESPONSE,
  __module__ = 'domain_service_pb2'
  # @@protoc_insertion_point(class_scope:domainmessages.SuspendDomainsResponse)
  ))
_sym_db.RegisterMessage(SuspendDomainsResponse)

UnSuspendDomainsRequest = _reflection.GeneratedProtocolMessageType('UnSuspendDomainsRequest', (_message.Message,), dict(
  DESCRIPTOR = _UNSUSPENDDOMAINSREQUEST,
  __module__ = 'domain_service_pb2'
  # @@protoc_insertion_point(class_scope:domainmessages.UnSuspendDomainsRequest)
  ))
_sym_db.RegisterMessage(UnSuspendDomainsRequest)

UnSuspendDomainsResponse = _reflection.GeneratedProtocolMessageType('UnSuspendDomainsResponse', (_message.Message,), dict(
  DESCRIPTOR = _UNSUSPENDDOMAINSRESPONSE,
  __module__ = 'domain_service_pb2'
  # @@protoc_insertion_point(class_scope:domainmessages.UnSuspendDomainsResponse)
  ))
_sym_db.RegisterMessage(UnSuspendDomainsResponse)

DomainInfoRequest = _reflection.GeneratedProtocolMessageType('DomainInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOMAININFOREQUEST,
  __module__ = 'domain_service_pb2'
  # @@protoc_insertion_point(class_scope:domainmessages.DomainInfoRequest)
  ))
_sym_db.RegisterMessage(DomainInfoRequest)

DomainInfoResponse = _reflection.GeneratedProtocolMessageType('DomainInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _DOMAININFORESPONSE,
  __module__ = 'domain_service_pb2'
  # @@protoc_insertion_point(class_scope:domainmessages.DomainInfoResponse)
  ))
_sym_db.RegisterMessage(DomainInfoResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\002pb'))

_DOMAINSERVICE = _descriptor.ServiceDescriptor(
  name='DomainService',
  full_name='domainmessages.DomainService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=449,
  serialized_end=864,
  methods=[
  _descriptor.MethodDescriptor(
    name='SuspendDomains',
    full_name='domainmessages.DomainService.SuspendDomains',
    index=0,
    containing_service=None,
    input_type=_SUSPENDDOMAINSREQUEST,
    output_type=_SUSPENDDOMAINSRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\036\"\031/v1/domains/suspenddomain:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='UnSuspendDomains',
    full_name='domainmessages.DomainService.UnSuspendDomains',
    index=1,
    containing_service=None,
    input_type=_UNSUSPENDDOMAINSREQUEST,
    output_type=_UNSUSPENDDOMAINSRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002 \"\033/v1/domains/unsuspenddomain:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='DomainInfo',
    full_name='domainmessages.DomainService.DomainInfo',
    index=2,
    containing_service=None,
    input_type=_DOMAININFOREQUEST,
    output_type=_DOMAININFORESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\033\"\026/v1/domains/domaininfo:\001*')),
  ),
])
_sym_db.RegisterServiceDescriptor(_DOMAINSERVICE)

DESCRIPTOR.services_by_name['DomainService'] = _DOMAINSERVICE

# @@protoc_insertion_point(module_scope)