---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "brand-detection"
  namespace: "abuse-api-prod"
  labels:
    app: "brand-detection"
spec:
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: "brand-detection"
    spec:
      imagePullSecrets:
        -
          name: "k8s-artifactory-creds"
      containers:
        -
          name: "brand-detection"
          imagePullPolicy: "Always"
          image: "artifactory.secureserver.net:10014/docker-dcu-local/brand_detection:REPLACE_WITH_GIT_COMMIT"
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: prod
          - name: KEYFILE
            value: /keyfiles/key.txt
          - name: REDIS
            value: brand-detection-redis.abuse-api-prod.svc.cluster.local
          - name: DOMAIN_SERVICE_URL
            value: domainservice.abuse-api-prod.svc.cluster.local:9000
          volumeMounts:
          - name: encryption-keys
            mountPath: /keyfiles
            readOnly: true

      volumes:
        - name: encryption-keys
          secret:
            secretName: encryption-key-files

