---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "brand-detection"
  namespace: "abuse-api-prod"
  labels:
    app: "brand-detection"
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "brand-detection"
  template:
    metadata:
      labels:
        app: "brand-detection"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "brand-detection"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/brand_detection:REPLACE_WITH_GIT_COMMIT"
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: prod
          - name: KEYFILE
            value: /keyfiles/key.txt
          - name: REDIS
            value: brand-detection-redis.abuse-api-prod.svc.cluster.local
          - name: DOMAIN_SERVICE_URL
            value: domainservice.abuse-api-prod.svc.cluster.local:9000
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: secret
          volumeMounts:
          - name: encryption-keys
            mountPath: /keyfiles
            readOnly: true

      volumes:
        - name: encryption-keys
          secret:
            secretName: encryption-key-files

