---
apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "brand-detection"
  namespace: "abuse-api-prod"
spec:
  tls:
    - hosts:
      - "branddetection.int.godaddy.com"
      secretName: tls-brand-detection
  rules:
  - host: "branddetection.int.godaddy.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: "brand-detection"
          servicePort: 5000