apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- brand_detection.ingress.yaml

namespace: abuse-api-prod
images:
- name: docker-dcu-local.artifactory.secureserver.net/brand_detection
  newTag: prod
replicas:
  - count: 2
    name: brand-detection

configMapGenerator:
- literals:
  - sysenv=prod
  - REDIS=brand-detection-redis.abuse-api-prod.svc.cluster.local
  - KEYFILE=/keyfiles/key.txt
  - DOMAIN_SERVICE_URL=domainservice.abuse-api-prod.svc.cluster.local:9000
  name: env-specific-values
