---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "brand-detection"
  namespace: "abuse-api-ote"
  labels:
    app: "brand-detection"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "brand-detection"
    spec:
      imagePullSecrets:
        -
          name: "k8s-artifactory-creds"
      containers:
        -
          name: "brand-detection"
          imagePullPolicy: "Always"
          image: "artifactory.secureserver.net:10014/docker-dcu-local/brand_detection:ote"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: sysenv
            value: ote
          - name: KEYFILE
            value: /keyfiles/key.txt
          # redis used for a CELERY backend
          - name: REDIS
            value: brand-detection-redis.abuse-api-ote.svc.cluster.local
          volumeMounts:
          - name: encryption-keys
            mountPath: /keyfiles
            readOnly: true

      volumes:
        - name: encryption-keys
          secret:
            secretName: encryption-key-files

