apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- brand_detection.ingress.yaml

namespace: abuse-api-ote
images:
- name: gdartifactory1.jfrog.io/docker-dcu-local/brand_detection
  newTag: ote

configMapGenerator:
- literals:
  - sysenv=ote
  - REDIS=brand-detection-redis.abuse-api-ote.svc.cluster.local
  - DOMAIN_SERVICE_URL=domainservice.abuse-api-ote.svc.cluster.local:9000
  name: env-specific-values
