---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "brand-detection"
  labels:
    app: "brand-detection"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "brand-detection"
  template:
    metadata:
      labels:
        app: "brand-detection"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "brand-detection"
          image: "docker-dcu-local.artifactory.secureserver.net/brand_detection"
          envFrom:
            - configMapRef:
                name: env-specific-values
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: secret
